### ISSUE TITLE
Incorrect initial redux state

### ISSUE THREAD

**Issue by kachkaev** [graphcool-examples/react-apollo-todo-example#4]
This piece of code seems to result a warning:

```js
const store = createStore(
  combineReducers({
    filter,
    apollo: client.reducer(),
  }),
  applyMiddleware(client.middleware()),
  window.devToolsExtension ? window.devToolsExtension() : f => f
)
```

> `warning.js:14 The previous state received by the reducer has unexpected type of "Function". Expected argument to be an object with the following keys: "filter", "apollo"`

Passing an empty object as a second argument to `createStore` fixes this:
```js
const store = createStore(
  combineReducers({
    filter,
    apollo: client.reducer(),
  }),
  {}, // <- this one
  applyMiddleware(client.middleware()),
  window.devToolsExtension ? window.devToolsExtension() : f => f
)
```

Not submitting a PR because I'm not 100% sure in my conclusions.

**Comment by marktani** [comment]
thanks for your issue, will look into this soon :slightly_smiling_face:

**Comment by marktani** [comment]
I upgraded a lot of packages and also correclty initialize the state now. :+1:
